Department-Store/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Department_Store.Models;
using PagedList;

namespace Department_Store.Controllers
{
    public class AdminController : Controller
    {
        DbStore data = new DbStore();

        public ActionResult Index(int? page)
        {
            
            if (page == null) page = 1;
            var item = (from hh in data.SanPhams select hh).Where(m => m.Slgton > 0).OrderBy(m => m.MaSP); ;
            int pageSize = 10;
            int pageNum = page ?? 1;
            return View(item.ToPagedList(pageNum, pageSize));
        }
        [Authorize]
        public ActionResult ThemSP()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemSP(FormCollection collection, SanPham sp)
        {

            var S_TenSP = collection["TenSP"];
            var S_GiaSP = Convert.ToDecimal(collection["GiaSP"]);
            var S_Slgton = Convert.ToInt32(collection["Slgton"]);
            var S_HinhSP = collection["HinhSP"];
            var S_NgayNhap = Convert.ToDateTime(collection["NgayNhap"]);
            if (string.IsNullOrEmpty(S_TenSP))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                sp.TenSP = S_TenSP.ToString();
                sp.HinhSP = S_HinhSP.ToString();
                sp.GiaSP = (int?)S_GiaSP;
                sp.NgayNhap = S_NgayNhap;
                sp.Slgton = S_Slgton;
                data.SanPhams.Add(sp);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return this.ThemSP();
        }
        public ActionResult SuaSP(int id)
        {
            var S_sanpham = data.SanPhams.First(m => m.MaSP == id);
            return View(S_sanpham);
        }
        [HttpPost]
        public ActionResult SuaSP(int id, FormCollection collection)
        {
            var S_sanpham = data.SanPhams.First(m => m.MaSP == id);
            var S_TenSP = collection["TenSP"];
            var S_HinhSP = collection["HinhSP"];
            var S_GiaSP = Convert.ToDecimal(collection["GiaSP"]);
            var S_NgayNhap = Convert.ToDateTime(collection["NgayNhap"]);
            var S_Slgton = Convert.ToInt32(collection["SlgTon"]);
            S_sanpham.MaSP = id;
            if (string.IsNullOrEmpty(S_TenSP))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                S_sanpham.TenSP = S_TenSP;
                S_sanpham.HinhSP = S_HinhSP;
                S_sanpham.GiaSP = (int?)S_GiaSP;
                S_sanpham.NgayNhap = S_NgayNhap;
                S_sanpham.Slgton = S_Slgton;
                UpdateModel(S_sanpham);
                data.SaveChanges();
                return RedirectToAction("Index");
            }
            return this.SuaSP(id);

        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }
        public ActionResult XoaSP(int id)
        {
            var D_sp = data.SanPhams.First(m => m.MaSP == id);
            return View(D_sp);
        }
        [HttpPost]
        public ActionResult XoaSP(int id, FormCollection collection)
        {
            var D_sp = data.SanPhams.Where(m => m.MaSP == id).First();
            data.SanPhams.Remove(D_sp);
            data.SaveChanges();
            return RedirectToAction("Index");

        }
        private double TongDoanhThu()
        {
            double dt = 0;
            List<HoaDon> tdt = Session["HoaDon"] as List<HoaDon>;
            if (tdt != null)
            {
                dt = Convert.ToDouble(tdt.Sum(n => n.ThanhTien));
            }
            return dt;
        }
        public ActionResult DoanhThu(FormCollection collection)
        {
            int dt = 0;
            List<HoaDon> hd = new List<HoaDon>();
            foreach (HoaDon hoaDon in hd)
            {
                dt += Convert.ToInt32(hoaDon.ThanhTien);
            }
            return PartialView(dt);
        }
    }

}

Department-Store/Controllers/DanhMucController.cs
using Department_Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Department_Store.Controllers
{
    public class DanhMucController : Controller
    {

        DbStore data = new DbStore();
        // GET: Danhmuc
        public ActionResult DanhMuc()
        {
            var listdm = from dm in data.DanhMucs select dm;
            return PartialView(listdm);
        }
        public ActionResult DanhMucAdmin()
        {
            var listdm = from dm in data.DanhMucs select dm;
            return View(listdm);
        }
        public ActionResult DanhMucSP(int id)
        {
            var list = data.SanPhams.Where(m => m.MaDM == id).ToList();
            return View(list);
        }
        public ActionResult ThemDM()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemDM(FormCollection collection, DanhMuc dm)
        {

            var S_TenDM = collection["TenDM"];
            if (string.IsNullOrEmpty(S_TenDM))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                dm.TenDM = S_TenDM.ToString();
                data.DanhMucs.Add(dm);
                data.SaveChanges();
                return RedirectToAction("DanhMucAdmin");
            }
            return this.ThemDM();
        }
        public ActionResult XoaDM(int id, FormCollection collection)
        {
            var D_dm = data.DanhMucs.Where(m => m.MaDM == id).First();
            data.DanhMucs.Remove(D_dm);
            data.SaveChanges();
            return RedirectToAction("DanhMucAdmin");

        }
    }
}

Department-Store/Controllers/DonHangController.cs
using Department_Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Department_Store.Controllers
{
    public class DonHangController : Controller
    {
        DbStore data = new DbStore();
        // GET: DonHang

        public ActionResult XemDonHang(int? id)
        {
            var donhang = (from dh in data.DonHangs select dh);
            return View(donhang);
        }
        public ActionResult XemChiTietDonHang(int? id)
        {
            var ctdonhang = (from dh in data.ChiTietDonHangs select dh).Where(m => m.madon == id).First(); 
            return View(ctdonhang);
        }
        //public ActionResult HuyDonHang(int id, FormCollection collection)
        //{
        //    var D_ctdh = data.ChiTietDonHangs.Where(m => m.madon == id).First();
        //    data.ChiTietDonHangs.Remove(D_ctdh);
        //    data.SaveChanges();
        //    return RedirectToAction("Index");

        //}
    }
}

Department-Store/Controllers/StoreController.cs
using Department_Store.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Web.UI;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;

namespace Department_Store.Controllers
{
    public class StoreController : Controller
    {
        DbStore data = new DbStore();
        // GET: Store
        public ActionResult Home(int? page)
        {
            if (page == null) page = 1;
            var item = (from hh in data.SanPhams select hh).Where(m => m.Slgton > 0).OrderBy(m => m.MaSP); ;
            int pageSize = 8;
            int pageNum = page ?? 1;
            return View(item.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Search(int? page, string Search)
        {
            ViewBag.KeyWord = Search;
            if (page == null) page = 1;
            var item = (from hh in data.SanPhams select hh).Where(m => m.Slgton > 0 && m.TenSP.Contains(Search)).OrderBy(m => m.MaSP); ;
            int pageSize = 8;
            int pageNum = page ?? 1;
            return View(item.ToPagedList(pageNum, pageSize));
        }
        public ActionResult ThongTinSP(int? id)
        {
            var item = data.SanPhams.Where(m => m.MaSP == id).First();
            return View(item);
        }
    }
}

Department-Store/Views/Admin/Index.cshtml
@model PagedList.IPagedList<Department_Store.Models.SanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <tr class="text-center">
        <th>@Html.ActionLink("Sản phẩm", "Index", "Admin", new { area = "" }, new { @class = "nav-link" }) </th>
        <th>@Html.ActionLink("Danh Mục", "DanhMucAdmin", "DanhMuc", new { area = "" }, new { @class = "nav-link" })</th>
        <th>@Html.ActionLink("Đơn Hàng", "XemDonHang", "DonHang", new { area = "" }, new { @class = "nav-link" })</th>

    </tr>
</table>

<h2 class="text-center">Sản Phẩm <br />@Html.ActionLink("Thêm sản phẩm", "ThemSP", new { area = "" }, new { @class = "btn btn-primary" })</h2>

<table class="table">
    <tr class="text-center">
        <th> Mã hàng </th>
        <th> Tên hàng</th>
        <th> Giá </th>
        <th> Số lượng tồn</th>
        <th> Hình </th>
        <th> Ngày nhập </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@Html.DisplayFor(modelItem => item.MaSP)</td>
            <td>@Html.DisplayFor(modelItem => item.TenSP)</td>
            <td>@Html.DisplayFor(modelItem => item.GiaSP)</td>
            <td>@Html.DisplayFor(modelItem => item.Slgton)</td>
            <td><img src="@item.HinhSP" alt="hinh thumbnail" width="75%" height="75%" /></td>

            <td>@Html.DisplayFor(modelItem => item.NgayNhap)</td>
            <td>
                @Html.ActionLink(" ", "SuaSP", new { id = item.MaSP }, new { @class = "bi bi-pen" })|
                @Html.ActionLink(" ", "ThongTinSP", "Store", new { id = item.MaSP }, new { @class = "bi bi-info-lg" })|

                @Html.ActionLink(" ", "XoaSP", new { id = item.MaSP }, new { @class = "bi bi-trash" })
            </td>
        </tr>
    }
</table>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

Department-Store/Views/Admin/SuaSP.cshtml
@model Department_Store.Models.SanPham

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSP)

<div class="form-group">
    <br />
    <h6>Tên Sản Phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <br />
    <h6>Giá bán sản phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.GiaSP, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.GiaSP, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <br />
    <h6>Số lượng sản phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.Slgton, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Slgton, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    <br />
    <h6>Hình sản phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.HinhSP, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.HinhSP, "", new { @class = "text-danger" })
    </div>
</div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                   style="display:none;" />
            <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            <img src="@Model.HinhSP" id="pictureUpload" />
        </div>
    </div>
    @section upload
{
        <script>
            $(function () {
                $('#btnUpload').click(function () {
                    $('#fileUpload').trigger('click');
                });
            });
            $('#fileUpload').change(function () {
                if (window.FormData !== undefined) {
                    var fileUpload = $('#fileUpload').get(0);
                    var files = fileUpload.files;
                    var formData = new FormData();
                    formData.append('file', files[0]);

                    $.ajax(
                        {
                            type: 'POST',
                            url: '/Home/ProcessUpload',
                            contentType: false,
                            processData: false,
                            data: formData,
                            success: function (urlImage) {

                                $('#pictureUpload').attr('src', urlImage);
                                $('#HinhSP').val(urlImage);
                            },
                            error: function (err) {
                                alert('Error ', err.statusText);
                            }
                        });
                }
            });
        </script>
    }

<div class="form-group">
    <br />
    <h6>Ngày nhập sản phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.NgayNhap, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NgayNhap, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <br />
    <h6>Mã danh mục Sản Phẩm</h6>
    <div class="col-md-10">
        @Html.EditorFor(model => model.MaDM, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
    </div>
</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <br />
            <input type="submit" value="Save" class="btn btn-outline-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Department-Store/Views/Admin/ThemDM.cshtml
@model Department_Store.Models.DanhMuc

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhMuc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenDM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Department-Store/Views/Admin/ThemSP.cshtml
@model Department_Store.Models.SanPham

@{
    ViewBag.Title = "ThemSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm sản phẩm</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <br />
                <h6>Tên Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <br />
                <h6>Giá bán Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GiaSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GiaSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <br />
                <h6>Số lượng Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Slgton, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Slgton, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <br />
                <h6>Hình Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HinhSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HinhSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                           style="display:none;" />
                    <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
                    <img src="" id="pictureUpload" />
                </div>
            </div>
            @section upload
{
                <script>
                    $(function () {
                        $('#btnUpload').click(function () {
                            $('#fileUpload').trigger('click');
                        });
                    });
                    $('#fileUpload').change(function () {
                        if (window.FormData !== undefined) {
                            var fileUpload = $('#fileUpload').get(0);
                            var files = fileUpload.files;
                            var formData = new FormData();
                            formData.append('file', files[0]);

                            $.ajax(
                                {
                                    type: 'POST',
                                    url: '/Admin/ProcessUpload',
                                    contentType: false,
                                    processData: false,
                                    data: formData,
                                    success: function (urlImage) {

                                        $('#pictureUpload').attr('src', urlImage);
                                        $('#HinhSP').val(urlImage);
                                    },
                                    error: function (err) {
                                        alert('Error ', err.statusText);
                                    }
                                });
                        }
                    });
                </script>
            }
            <div class="form-group">
                <br />
                <h6>Ngày nhập Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgayNhap, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayNhap, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <br />
                <h6>Mã Danh mục Sản Phẩm</h6>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaDM, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Department-Store/Views/Admin/XoaSP.cshtml
@model Department_Store.Models.SanPham

@{
    ViewBag.Title = "XoaSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Bạn muốn xoá sản phẩm này?</h3>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.TenSP)</th>
        <th>@Html.DisplayNameFor(model => model.HinhSP)</th>
        <th>@Html.DisplayNameFor(model => model.GiaSP)</th>
        <th>@Html.DisplayNameFor(model => model.Slgton)</th>
        <th>@Html.DisplayNameFor(model => model.NgayNhap)</th>
        <th>@Html.DisplayNameFor(model => model.MaDM)</th>
    </tr>
    <tr>
        <td>@Html.DisplayFor(model => model.TenSP)</td>
        <td><img src="@Html.DisplayFor(model => model.HinhSP)" width="180" /></td>
        <td>@Html.DisplayFor(model => model.GiaSP)</td>
        <td>@Html.DisplayFor(model => model.Slgton)</td>
        <td>@Html.DisplayFor(model => model.NgayNhap)</td>
        <td></td>
    </tr>
</table>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
}